main_file = open("big.txt","r")
chunk1 = open("chunk1.txt", "w")
chunk2 = open("chunk2.txt", "w")
chunk3 = open("chunk3.txt", "w")
chunk4 = open("chunk4.txt", "w")
chunk5 = open("chunk5.txt", "w")
chunk6 = open("chunk6.txt", "w")
chunk7 = open("chunk7.txt", "w")
chunk8 = open("chunk8.txt", "w")
chunk9 = open("chunk9.txt", "w")
chunk10 = open("chunk10.txt", "w")
chunk11 = open("chunk11.txt", "w")
chunk12 = open("chunk12.txt", "w")
chunk13 = open("chunk13.txt", "w")
chunk14 = open("chunk14.txt", "w")
chunk15 = open("chunk15.txt", "w")
chunk16 = open("chunk16.txt", "w")
chunk17 = open("chunk17.txt", "w")
chunk18 = open("chunk18.txt", "w")
chunk19 = open("chunk19.txt", "w")
chunk20 = open("chunk20.txt", "w")


for i in range(1,21):
    line = main_file.readline()
    eval(f"chunk{i}").write(line)

main_file.close()
chunk1.close()
chunk2.close()
chunk3.close()
chunk4.close()
chunk5.close()
chunk6.close()
chunk7.close()
chunk8.close()
chunk9.close()
chunk10.close()
chunk11.close()
chunk12.close()
chunk13.close()
chunk14.close()
chunk15.close()
chunk16.close()
chunk17.close()
chunk18.close()
chunk19.close()
chunk20.close()
